version: '3.9'
services:
  postgres:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - postgres
networks:
  postgres:

