// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cage is the predicate function for cage builders.
type Cage func(*sql.Selector)

// Dinosaur is the predicate function for dinosaur builders.
type Dinosaur func(*sql.Selector)
