// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/samsonannan/prizepicks-assessment/pkg/ent/cage"
	"github.com/samsonannan/prizepicks-assessment/pkg/ent/dinosaur"
	"github.com/samsonannan/prizepicks-assessment/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cageMixin := schema.Cage{}.Mixin()
	cageMixinFields0 := cageMixin[0].Fields()
	_ = cageMixinFields0
	cageFields := schema.Cage{}.Fields()
	_ = cageFields
	// cageDescCreatedAt is the schema descriptor for created_at field.
	cageDescCreatedAt := cageMixinFields0[0].Descriptor()
	// cage.DefaultCreatedAt holds the default value on creation for the created_at field.
	cage.DefaultCreatedAt = cageDescCreatedAt.Default.(func() time.Time)
	// cageDescUpdatedAt is the schema descriptor for updated_at field.
	cageDescUpdatedAt := cageMixinFields0[1].Descriptor()
	// cage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cage.DefaultUpdatedAt = cageDescUpdatedAt.Default.(func() time.Time)
	// cage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cage.UpdateDefaultUpdatedAt = cageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cageDescSize is the schema descriptor for size field.
	cageDescSize := cageFields[1].Descriptor()
	// cage.DefaultSize holds the default value on creation for the size field.
	cage.DefaultSize = cageDescSize.Default.(int64)
	// cage.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	cage.SizeValidator = cageDescSize.Validators[0].(func(int64) error)
	// cageDescCapacity is the schema descriptor for capacity field.
	cageDescCapacity := cageFields[2].Descriptor()
	// cage.DefaultCapacity holds the default value on creation for the capacity field.
	cage.DefaultCapacity = cageDescCapacity.Default.(int64)
	// cage.CapacityValidator is a validator for the "capacity" field. It is called by the builders before save.
	cage.CapacityValidator = cageDescCapacity.Validators[0].(func(int64) error)
	// cageDescID is the schema descriptor for id field.
	cageDescID := cageFields[0].Descriptor()
	// cage.DefaultID holds the default value on creation for the id field.
	cage.DefaultID = cageDescID.Default.(func() uuid.UUID)
	dinosaurMixin := schema.Dinosaur{}.Mixin()
	dinosaurMixinFields0 := dinosaurMixin[0].Fields()
	_ = dinosaurMixinFields0
	dinosaurFields := schema.Dinosaur{}.Fields()
	_ = dinosaurFields
	// dinosaurDescCreatedAt is the schema descriptor for created_at field.
	dinosaurDescCreatedAt := dinosaurMixinFields0[0].Descriptor()
	// dinosaur.DefaultCreatedAt holds the default value on creation for the created_at field.
	dinosaur.DefaultCreatedAt = dinosaurDescCreatedAt.Default.(func() time.Time)
	// dinosaurDescUpdatedAt is the schema descriptor for updated_at field.
	dinosaurDescUpdatedAt := dinosaurMixinFields0[1].Descriptor()
	// dinosaur.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dinosaur.DefaultUpdatedAt = dinosaurDescUpdatedAt.Default.(func() time.Time)
	// dinosaur.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dinosaur.UpdateDefaultUpdatedAt = dinosaurDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dinosaurDescName is the schema descriptor for name field.
	dinosaurDescName := dinosaurFields[1].Descriptor()
	// dinosaur.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dinosaur.NameValidator = dinosaurDescName.Validators[0].(func(string) error)
	// dinosaurDescSpecies is the schema descriptor for species field.
	dinosaurDescSpecies := dinosaurFields[2].Descriptor()
	// dinosaur.SpeciesValidator is a validator for the "species" field. It is called by the builders before save.
	dinosaur.SpeciesValidator = dinosaurDescSpecies.Validators[0].(func(string) error)
	// dinosaurDescID is the schema descriptor for id field.
	dinosaurDescID := dinosaurFields[0].Descriptor()
	// dinosaur.DefaultID holds the default value on creation for the id field.
	dinosaur.DefaultID = dinosaurDescID.Default.(func() uuid.UUID)
}
