// Code generated by ent, DO NOT EDIT.

package dinosaur

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/samsonannan/prizepicks-assessment/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldName, v))
}

// Species applies equality check predicate on the "species" field. It's identical to SpeciesEQ.
func Species(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldSpecies, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldContainsFold(FieldName, v))
}

// SpeciesEQ applies the EQ predicate on the "species" field.
func SpeciesEQ(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldSpecies, v))
}

// SpeciesNEQ applies the NEQ predicate on the "species" field.
func SpeciesNEQ(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldSpecies, v))
}

// SpeciesIn applies the In predicate on the "species" field.
func SpeciesIn(vs ...string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldSpecies, vs...))
}

// SpeciesNotIn applies the NotIn predicate on the "species" field.
func SpeciesNotIn(vs ...string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldSpecies, vs...))
}

// SpeciesGT applies the GT predicate on the "species" field.
func SpeciesGT(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGT(FieldSpecies, v))
}

// SpeciesGTE applies the GTE predicate on the "species" field.
func SpeciesGTE(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldGTE(FieldSpecies, v))
}

// SpeciesLT applies the LT predicate on the "species" field.
func SpeciesLT(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLT(FieldSpecies, v))
}

// SpeciesLTE applies the LTE predicate on the "species" field.
func SpeciesLTE(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldLTE(FieldSpecies, v))
}

// SpeciesContains applies the Contains predicate on the "species" field.
func SpeciesContains(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldContains(FieldSpecies, v))
}

// SpeciesHasPrefix applies the HasPrefix predicate on the "species" field.
func SpeciesHasPrefix(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldHasPrefix(FieldSpecies, v))
}

// SpeciesHasSuffix applies the HasSuffix predicate on the "species" field.
func SpeciesHasSuffix(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldHasSuffix(FieldSpecies, v))
}

// SpeciesEqualFold applies the EqualFold predicate on the "species" field.
func SpeciesEqualFold(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEqualFold(FieldSpecies, v))
}

// SpeciesContainsFold applies the ContainsFold predicate on the "species" field.
func SpeciesContainsFold(v string) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldContainsFold(FieldSpecies, v))
}

// GroupEQ applies the EQ predicate on the "group" field.
func GroupEQ(v Group) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldEQ(FieldGroup, v))
}

// GroupNEQ applies the NEQ predicate on the "group" field.
func GroupNEQ(v Group) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNEQ(FieldGroup, v))
}

// GroupIn applies the In predicate on the "group" field.
func GroupIn(vs ...Group) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldIn(FieldGroup, vs...))
}

// GroupNotIn applies the NotIn predicate on the "group" field.
func GroupNotIn(vs ...Group) predicate.Dinosaur {
	return predicate.Dinosaur(sql.FieldNotIn(FieldGroup, vs...))
}

// HasCage applies the HasEdge predicate on the "cage" edge.
func HasCage() predicate.Dinosaur {
	return predicate.Dinosaur(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CageTable, CageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCageWith applies the HasEdge predicate on the "cage" edge with a given conditions (other predicates).
func HasCageWith(preds ...predicate.Cage) predicate.Dinosaur {
	return predicate.Dinosaur(func(s *sql.Selector) {
		step := newCageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Dinosaur) predicate.Dinosaur {
	return predicate.Dinosaur(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Dinosaur) predicate.Dinosaur {
	return predicate.Dinosaur(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Dinosaur) predicate.Dinosaur {
	return predicate.Dinosaur(func(s *sql.Selector) {
		p(s.Not())
	})
}
